import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { UserOptions } from 'jspdf-autotable';

interface ExportData {
  prediction: string;
  confidence: number;
  timestamp: string;
  text: string;
}

interface jsPDFWithPlugin extends jsPDF {
  autoTable: (options: UserOptions) => jsPDF;
  lastAutoTable: {
    finalY: number;
  };
}

export const exportResultToPDF = (data: ExportData) => {
  const doc = new jsPDF() as jsPDFWithPlugin;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('Fake News Detection AI', 14, 20);

  doc.setFontSize(10);
  doc.text('Premium Verification Report', 14, 30);
  doc.text(new Date(data.timestamp).toLocaleString(), 160, 30);

  // Results Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('Analysis Summary', 14, 55);

  const isReal = data.prediction === 'Real News';
  const predictionColor = isReal ? [16, 185, 129] : [239, 68, 68];

  doc.autoTable({
    startY: 60,
    head: [['Attribute', 'Value']],
    body: [
      ['Prediction', data.prediction],
      ['AI Confidence Score', `${data.confidence.toFixed(2)}%`],
      ['Verification Status', isReal ? 'Verified Authentic' : 'Potential Misinformation'],
    ],
    headStyles: { fillColor: [59, 130, 246] },
    columnStyles: {
      1: { fontStyle: 'bold' }
    },
    didParseCell: (cellData) => {
      if (cellData.section === 'body' && cellData.column.index === 1 && cellData.row.index === 0) {
        cellData.cell.styles.textColor = predictionColor as [number, number, number];
      }
    }
  });

  // Content Section
  const finalY = doc.lastAutoTable.finalY + 20;
  doc.setFontSize(14);
  doc.text('Analyzed Content', 14, finalY);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const splitText = doc.splitTextToSize(data.text, 180);
  doc.text(splitText, 14, finalY + 10);

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Fake News Detection AI Service. This report is for informational purposes only.', 14, pageHeight - 10);

  doc.save(`Verification_Report_${new Date().getTime()}.pdf`);
};
